/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author 1205088
 */
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import net.proteanit.sql.DbUtils;
public class class6 extends javax.swing.JFrame {

    /**
     * Creates new form class6
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst=null;
    String myclass=null;
    public class6() {
        initComponents();
        conn = projectconnect.ConnecrDb();
        login myob=new login();
        search_id.setText(myob.headteacher);
        System.out.println(myob.headteacher);
        Update_table();
    }
     public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
      private void Update_table(){
        try{
            
            if(subjectbox.getSelectedItem().equals("Bangla 1st"))myclass="bangla1";
                else if(subjectbox.getSelectedItem().equals("Bangla 2nd"))myclass="bangla2";
                else if(subjectbox.getSelectedItem().equals("English 1st"))myclass="english1";
                else if(subjectbox.getSelectedItem().equals("English 2nd"))myclass="english2";
                else if(subjectbox.getSelectedItem().equals("General Math"))myclass="generalmath";
                else if(subjectbox.getSelectedItem().equals("Agriculture"))myclass="agriculture";
                else if(subjectbox.getSelectedItem().equals("Physics"))myclass="physics";
                else if(subjectbox.getSelectedItem().equals("Chemistry"))myclass="chemistry";
                else if(subjectbox.getSelectedItem().equals("Higher Math"))myclass="highermath";
                else if(subjectbox.getSelectedItem().equals("ICT"))myclass="ict";
                else if(subjectbox.getSelectedItem().equals("Islam"))myclass="islam";
                else if(subjectbox.getSelectedItem().equals("Sociology"))myclass="sociology";
                else if(subjectbox.getSelectedItem().equals("General Science"))myclass="generalscience";
                else if(subjectbox.getSelectedItem().equals("Career studies"))myclass="lifecareer";
                else if(subjectbox.getSelectedItem().equals("Hindu Studies"))myclass="hindu";
                
        String sql = "select * from '"+myclass+"' ";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        subject_table.setModel(DbUtils.resultSetToTableModel(rs));

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }finally{
            try{
                rs.close();
                pst.close();
                
            }
            catch(Exception e){

            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            ImageIcon icon = new ImageIcon("images/back.jpg");
            Image img = icon.getImage();
            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                g.drawImage(img,0,0,null);
                //        g.drawImage(newimage, 0, 0, this);
            }

            @Override
            public Dimension getPreferredSize() {
                return new Dimension(812, 287);
            }
        };
        jScrollPane2 = new javax.swing.JScrollPane();
        subject_table = new javax.swing.JTable();
        jDesktopPane2 = new javax.swing.JDesktopPane(){
            ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("back.jpg"));
            Image img = icon.getImage();
            //Image newimage = img.getScaledInstance(812, 287, Image.SCALE_SMOOTH);

            @Override
            protected void paintComponent(Graphics g)
            {
                super.paintComponent(g);
                g.drawImage(img,0,0,null);
                //        g.drawImage(newimage, 0, 0, this);
            }

            @Override
            public Dimension getPreferredSize() {
                return new Dimension(812, 287);
            }

        }
        ;
        ct_parcentage = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        subjectbox = new javax.swing.JComboBox();
        semister = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        grade_txt = new javax.swing.JTextField();
        total_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        clear_txt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SID_txt = new javax.swing.JTextField();
        mcq_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ct_txt = new javax.swing.JTextField();
        attendance_txt = new javax.swing.JTextField();
        written_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        save_txt = new javax.swing.JButton();
        passcode_txt = new javax.swing.JTextField();
        att_mark = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        class_txt = new javax.swing.JLabel();
        class_type = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        search_id = new javax.swing.JTextField();
        update_button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        reslut_button = new javax.swing.JButton();
        teacher_button = new javax.swing.JButton();
        admission_button = new javax.swing.JButton();
        subject_button = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 0));

        subject_table.setBackground(new java.awt.Color(43, 42, 28));
        subject_table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(239, 225, 225), null, null));
        subject_table.setForeground(new java.awt.Color(254, 254, 251));
        subject_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        subject_table.setToolTipText("This is subject mark table");
        subject_table.setGridColor(new java.awt.Color(231, 232, 240));
        subject_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subject_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(subject_table);

        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jDesktopPane2.setBackground(new java.awt.Color(42, 42, 25));

        ct_parcentage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(5, 5, 5));
        jLabel1.setText("Select Subject : ");

        subjectbox.setBackground(new java.awt.Color(153, 153, 153));
        subjectbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bangla 1st", "Bangla 2nd", "English 1st", "English 2nd" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subjectbox, 0, 136, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(subjectbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        semister.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "semister 1", "semister 2", "semister 3", " " }));

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setText("Grade ");

        jLabel9.setText("Total");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(total_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(grade_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grade_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(254, 254, 254));
        jLabel11.setText("Semister : ");
        jLabel11.setBorder(null);

        jLabel14.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(254, 254, 254));
        jLabel14.setText("Passcode");

        clear_txt.setText("Clear");
        clear_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_txtActionPerformed(evt);
            }
        });

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 102), null, null));

        jLabel4.setText("Written");

        jLabel2.setText("StudentID");

        jLabel7.setText("Attendance");

        jLabel5.setText("MCQ");

        attendance_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                attendance_txtMouseExited(evt);
            }
        });
        attendance_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                attendance_txtKeyReleased(evt);
            }
        });

        jLabel6.setText("CT");

        jLabel3.setText("Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(SID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(written_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mcq_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(ct_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())
                    .addComponent(attendance_txt)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(written_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mcq_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ct_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attendance_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setText("CT percentage : ");
        jLabel12.setBorder(null);

        save_txt.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        save_txt.setText("Save");
        save_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_txtActionPerformed(evt);
            }
        });

        att_mark.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        class_txt.setBackground(new java.awt.Color(153, 153, 255));
        class_txt.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        class_txt.setForeground(new java.awt.Color(5, 5, 5));
        class_txt.setText("Select Class : ");

        class_type.setBackground(new java.awt.Color(204, 204, 204));
        class_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Class6", "CLass 7", "CLass 8", "CLass 9", "CLass 10", "CLass 6 admission" }));
        class_type.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(class_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(class_type, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(class_txt)
                    .addComponent(class_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel13.setBackground(new java.awt.Color(18, 18, 40));
        jLabel13.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(254, 254, 254));
        jLabel13.setText("Attendance percentag : ");
        jLabel13.setBorder(null);

        jDesktopPane2.setLayer(ct_parcentage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(semister, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(clear_txt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(save_txt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(passcode_txt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(att_mark, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(semister, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ct_parcentage, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(att_mark, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(save_txt)
                            .addComponent(clear_txt)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passcode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ct_parcentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(att_mark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passcode_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(save_txt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clear_txt)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        search_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_idActionPerformed(evt);
            }
        });
        search_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_idKeyReleased(evt);
            }
        });

        update_button.setText("Update");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Search ID :");

        jLayeredPane1.setLayer(search_id, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(update_button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_button)
                    .addComponent(search_id, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update_button)
                .addContainerGap())
        );

        jToolBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        reslut_button.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        reslut_button.setText("Result");
        reslut_button.setFocusable(false);
        reslut_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reslut_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        reslut_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reslut_buttonActionPerformed(evt);
            }
        });
        jToolBar1.add(reslut_button);

        teacher_button.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        teacher_button.setText("Teacher");
        teacher_button.setToolTipText("Teacher List");
        teacher_button.setFocusable(false);
        teacher_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        teacher_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        teacher_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacher_buttonActionPerformed(evt);
            }
        });
        jToolBar1.add(teacher_button);

        admission_button.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        admission_button.setText("Admission");
        admission_button.setToolTipText("class six admission module");
        admission_button.setFocusable(false);
        admission_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        admission_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        admission_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admission_buttonActionPerformed(evt);
            }
        });
        jToolBar1.add(admission_button);

        subject_button.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        subject_button.setText("Subeject");
        subject_button.setFocusable(false);
        subject_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        subject_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        subject_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject_buttonActionPerformed(evt);
            }
        });
        jToolBar1.add(subject_button);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDesktopPane1)
                            .addComponent(jDesktopPane2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_idActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_search_idActionPerformed
    String tot;
    int flag=0;
    private void attendance_txtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendance_txtMouseExited
        // TODO add your handling code here:
      //total_txt.setText(tot);
            

        
    }//GEN-LAST:event_attendance_txtMouseExited

    private void attendance_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_attendance_txtKeyReleased
        // TODO add your handling code here:
 
        
    }//GEN-LAST:event_attendance_txtKeyReleased

    private void save_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_txtActionPerformed
        // TODO add your handling code here:
        if(flag==0)
        {
            try {
                String sql=null;
                String subject_type=null;
                //sql="select '"+(String) subjectbox.getSelectedItem()+"'from passcode where Class = '"+(String) class_type.getSelectedItem()+"' ";
                
                
                if(subjectbox.getSelectedItem().equals("Bangla 1st"))subject_type="bangla1";
                else if(subjectbox.getSelectedItem().equals("Bangla 2nd"))subject_type="bangla2";
                else if(subjectbox.getSelectedItem().equals("English 1st"))subject_type="english1";
                else if(subjectbox.getSelectedItem().equals("English 2nd"))subject_type="english2";
                else if(subjectbox.getSelectedItem().equals("General Math"))subject_type="generalmath";
                else if(subjectbox.getSelectedItem().equals("Agriculture"))subject_type="agriculture";
                else if(subjectbox.getSelectedItem().equals("Physics"))subject_type="physics";
                else if(subjectbox.getSelectedItem().equals("Chemistry"))subject_type="chemistry";
                else if(subjectbox.getSelectedItem().equals("Higher Math"))subject_type="highermath";
                else if(subjectbox.getSelectedItem().equals("ICT"))subject_type="ict";
                else if(subjectbox.getSelectedItem().equals("Islam"))subject_type="islam";
                else if(subjectbox.getSelectedItem().equals("Sociology"))subject_type="sociology";
                else if(subjectbox.getSelectedItem().equals("General Science"))subject_type="generalscience";
                else if(subjectbox.getSelectedItem().equals("Career studies"))subject_type="career";
                else if(subjectbox.getSelectedItem().equals("Hindu Studies"))subject_type="hindu";
                sql="select "+subject_type+" from passcode where Class = '"+(String) class_type.getSelectedItem()+"' ";
                pst = conn.prepareStatement(sql);
                rs=pst.executeQuery();
                if(rs.next()){
                    if(passcode_txt.getText().equals(rs.getString(1)))flag=1;
                    System.out.println(rs.getString(1)+passcode_txt.getText()+flag);
                    rs.close();
                    pst.close();
                } 
            } catch (SQLException ex) {
                Logger.getLogger(class6.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        if(flag==1){
            double total = Double.valueOf(written_txt.getText())+Double.valueOf(mcq_txt.getText());
            double temp_mark=(Double.valueOf(ct_txt.getText())*Double.valueOf(ct_parcentage.getText())+Double.valueOf(attendance_txt.getText())*Double.valueOf(att_mark.getText()))/100.0;
            total=total*((100-(Double.valueOf(ct_parcentage.getText())+Double.valueOf(att_mark.getText()))))/100.0;

           // String table = subjectbox.getSelectedItem();
            String failed=null;
            tot = String.valueOf(total);
            total_txt.setText(tot);
            double gradepoint;
            if(total>=80){grade_txt.setText("A+");gradepoint=5.0;}
            else if(total>=70){grade_txt.setText("A");gradepoint=4.0;} 
            else if(total>=60){grade_txt.setText("A-");gradepoint=3.5;}
             else if(total>=50){grade_txt.setText("B");gradepoint=3.0;}
             else if(total>=40){grade_txt.setText("C");gradepoint=2.0;}
             else if(total>=33){grade_txt.setText("D");gradepoint=1.0;}
             else {

             grade_txt.setText("F");gradepoint=0.0;
             failed="Failed";
             }
            try{
                String sql = null;
                if(subjectbox.getSelectedItem().equals("Bangla 1st"))sql="insert into bangla1 values (?,?,?,?,?,?,?,?,?)";
                else if(subjectbox.getSelectedItem().equals("Bangla 2nd"))sql="insert into bangla2 values (?,?,?,?,?,?,?,?,?)";
                else if(subjectbox.getSelectedItem().equals("English 1st"))sql="insert into english1 values (?,?,?,?,?,?,?,?,?)";
                else if(subjectbox.getSelectedItem().equals("English 2nd"))sql="insert into english2 values (?,?,?,?,?,?,?,?,?)";
                else if(subjectbox.getSelectedItem().equals("General Math"))sql="insert into generalmath values (?,?,?,?,?,?,?,?,?)";
                else if(subjectbox.getSelectedItem().equals("Agriculture"))sql="insert into agriculture values (?,?,?,?,?,?,?,?,?)";
                else if(subjectbox.getSelectedItem().equals("Physics"))sql="insert into physics values (?,?,?,?,?,?,?,?,?)";
                else if(subjectbox.getSelectedItem().equals("Chemistry"))sql="insert into chemistry values (?,?,?,?,?,?,?,?,?)";
                else if(subjectbox.getSelectedItem().equals("Higher Math"))sql="insert into highermath values (?,?,?,?,?,?,?,?,?)";
                else if(subjectbox.getSelectedItem().equals("ICT"))sql="insert into ict values (?,?,?,?,?,?,?,?,?)";
                else if(subjectbox.getSelectedItem().equals("Islam"))sql="insert into islam values (?,?,?,?,?,?,?,?,?)";
                else if(subjectbox.getSelectedItem().equals("Sociology"))sql="insert into sociology values (?,?,?,?,?,?,?,?,?)";
                else if(subjectbox.getSelectedItem().equals("General Science"))sql="insert into generalscience values (?,?,?,?,?,?,?,?,?)";
                else if(subjectbox.getSelectedItem().equals("Career studies"))sql="insert into lifecareer values (?,?,?,?,?,?,?,?,?)";
                else if(subjectbox.getSelectedItem().equals("Hindu Studies"))sql="insert into hindu values (?,?,?,?,?,?,?,?,?)";
                pst=conn.prepareStatement(sql);
                pst.setString(1,SID_txt.getText());
                pst.setString(2,name_txt.getText());
                pst.setString(3,written_txt.getText());
                pst.setString(4,mcq_txt.getText());
                pst.setString(5,ct_txt.getText());
                pst.setString(6,attendance_txt.getText());
                pst.setString(7,total_txt.getText());
                pst.setString(8,grade_txt.getText());
                pst.setString(9, (String) class_type.getSelectedItem());
                pst.execute();
                //JOptionPane.showMessageDialog(null,"Saved");
                flag=0;
                 name_txt.setText("");written_txt.setText("");
                 mcq_txt.setText("");ct_txt.setText("");
                 attendance_txt.setText("");total_txt.setText("");
                 grade_txt.setText("");
                 int id=Integer.valueOf(SID_txt.getText());
                 id++;
                 String sql2=null;
                 String classtype = (String) class_type.getSelectedItem();
                 if(semister.getSelectedItem().equals("semister 1")) {

                     if(gradepoint<1)sql2="update '"+classtype+"' set TotalMark1 = TotalMark1 + '"+total+"',Grade1 =Grade1 + '"+gradepoint+"',Status1 = '"+failed+"' where SID = '"+SID_txt.getText()+"' ";
                     else sql2="update '"+classtype+"' set TotalMark1 = TotalMark1 + '"+total+"',Grade1 = Grade1 + '"+gradepoint+"' where SID = '"+SID_txt.getText()+"' ";
                 } 
                 else if(semister.getSelectedItem().equals("semister 2"))
                 {
                     if(gradepoint<1)sql2="update '"+classtype+"' set TotalMark2 = TotalMark2 + '"+total+"',Grade2 =Grade2 + '"+gradepoint+"',Status2 = '"+failed+"' where SID = '"+SID_txt.getText()+"' ";
                     else sql2="update '"+classtype+"' set TotalMark2 = TotalMark2 + '"+total+"',Grade2 =Grade2 + '"+gradepoint+"' where SID = '"+SID_txt.getText()+"' ";
                 }
                 else if(semister.getSelectedItem().equals("semister 3"))
                 {
                     if(gradepoint<1)sql2="update '"+classtype+"' set TotalMark3 = TotalMark3 + '"+total+"',Grade3 =Grade3 + '"+gradepoint+"',Status3 = '"+failed+"' where SID = '"+SID_txt.getText()+"' "; 
                     else sql2="update'"+classtype+"' set TotalMark3 = TotalMark3 + '"+total+"',Grade3 =Grade3 + '"+gradepoint+"' where SID = '"+SID_txt.getText()+"' ";
                 }
                 pst=conn.prepareStatement(sql2);
                 pst.executeUpdate();
    //////             SID_txt.setText(String.valueOf(id));
              String sql1="select SName from '"+classtype+"' where SID = '"+SID_txt.getText()+"' ";
                // pst.setString(1,SID_txt.getText());
                 pst=conn.prepareStatement(sql1);
                 rs=pst.executeQuery();
                 String ans= rs.getString("SName");
                 name_txt.setText(ans);

            
        
        }catch(SQLException | NumberFormatException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e);
        }
       }
        else if(flag==0)JOptionPane.showMessageDialog(null,"Sorry! You are not assigned for this task");
        Update_table();
    }//GEN-LAST:event_save_txtActionPerformed

    private void subject_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subject_tableMouseClicked
        // TODO add your handling code here:
        try{
            int row = subject_table.getSelectedRow();
            String Table_click = (subject_table.getModel().getValueAt(row,0).toString());
            String sql="select * from bangla1 where SID='"+Table_click+"'  ";
            pst = conn.prepareStatement(sql);
            rs= pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("SID");
                SID_txt.setText(add1);
                String add2=rs.getString("SName");
                name_txt.setText(add2);
                String add3=rs.getString("Written");
                written_txt.setText(add3);
                String add4=rs.getString("MCQ");
                mcq_txt.setText(add4);
                String add5=rs.getString("CT");
                ct_txt.setText(add5);
                String add6=rs.getString("Attendance");
                attendance_txt.setText(add6);
                String add7=rs.getString("Total");
                total_txt.setText(add7);
                String add8=rs.getString("Grade");
                grade_txt.setText(add8);
                String add9=rs.getString("Class");
                class_type.setSelectedItem(add9);


            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_subject_tableMouseClicked

    private void clear_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_txtActionPerformed
        // TODO add your handling code here:
        name_txt.setText("");written_txt.setText("");
            mcq_txt.setText("");ct_txt.setText("");
            attendance_txt.setText("");total_txt.setText("");
            grade_txt.setText("");
            SID_txt.setText("");
    }//GEN-LAST:event_clear_txtActionPerformed

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        // TODO add your handling code here:
        if(flag==0)
        {
            try {
                String sql=null;
                sql="select "+myclass+" from passcode where Class='"+(String) class_type.getSelectedItem()+"' ";
                pst = conn.prepareStatement(sql);
                rs=pst.executeQuery();
                if(rs.next()){
                    flag=1;
                } 
            } catch (SQLException ex) {
                Logger.getLogger(class6.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(flag==1){
            String mytablename=null;
            String sql=null;
            if(subjectbox.getSelectedItem().equals("Bangla 1st"))mytablename="bangla1";
                else if(subjectbox.getSelectedItem().equals("Bangla 2nd"))mytablename="bangla2"; 
                else if(subjectbox.getSelectedItem().equals("English 1st"))mytablename="english1";
                else if(subjectbox.getSelectedItem().equals("English 2nd"))mytablename="english2";
                else if(subjectbox.getSelectedItem().equals("General Math"))mytablename="generalmath"; 
                else if(subjectbox.getSelectedItem().equals("Agriculture"))mytablename="agriculture";
                else if(subjectbox.getSelectedItem().equals("Physics"))mytablename="physics";
                else if(subjectbox.getSelectedItem().equals("Chemistry"))mytablename="chemistry";
                else if(subjectbox.getSelectedItem().equals("Higher Math"))mytablename="highermath";
                else if(subjectbox.getSelectedItem().equals("ICT"))mytablename="ict";
                else if(subjectbox.getSelectedItem().equals("Islam"))mytablename="islam";
                else if(subjectbox.getSelectedItem().equals("Sociology"))mytablename="sociology";
                else if(subjectbox.getSelectedItem().equals("General Science"))mytablename="generalscience";// values (?,?,?,?,?,?,?,?,?)";
                else if(subjectbox.getSelectedItem().equals("Career studies"))mytablename="lifecareer";// values (?,?,?,?,?,?,?,?,?)";
                else if(subjectbox.getSelectedItem().equals("Hindu Studies"))mytablename="hindu";// values (?,?,?,?,?,?,?,?,?)";

           sql="update '"+mytablename+"' set SName='"+name_txt.getText()+"',Written= '"+written_txt.getText()+"',MCQ='"+mcq_txt.getText()+"',CT='"+ct_txt.getText()+"',Attendance='"+attendance_txt.getText()+"',Total='"+total_txt.getText()+"',Grade='"+grade_txt+"',Class='"+ (String) class_type.getSelectedItem()+"'where SID = '"+SID_txt.getText()+"' ";
            try {
                pst = conn.prepareStatement(sql);
                pst.executeUpdate();
                
            } catch (SQLException ex) {
                Logger.getLogger(class6.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else JOptionPane.showMessageDialog(null,"Sorry! You are not assigned for this task");
        Update_table();
    }//GEN-LAST:event_update_buttonActionPerformed

    private void search_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_idKeyReleased
        // TODO add your handling code here:
        try{
           
            String sql="select * from "+myclass+" where SID='"+search_id.getText()+"'  ";
            pst = conn.prepareStatement(sql);
            rs= pst.executeQuery();
            if(rs.next()){
                String add1=rs.getString("SID");
                SID_txt.setText(add1);
                String add2=rs.getString("SName");
                name_txt.setText(add2);
                String add3=rs.getString("Written");
                written_txt.setText(add3);
                String add4=rs.getString("MCQ");
                mcq_txt.setText(add4);
                String add5=rs.getString("CT");
                ct_txt.setText(add5);
                String add6=rs.getString("Attendance");
                attendance_txt.setText(add6);
                String add7=rs.getString("Total");
                total_txt.setText(add7);
                String add8=rs.getString("Grade");
                grade_txt.setText(add8);
                String add9=rs.getString("Class");
                class_type.setSelectedItem(add9);


            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_search_idKeyReleased

    private void subject_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
        new class6().setVisible(true);
    }//GEN-LAST:event_subject_buttonActionPerformed

    private void admission_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admission_buttonActionPerformed
        // TODO add your handling code here:dispose();
        new admission().setVisible(true);

    }//GEN-LAST:event_admission_buttonActionPerformed

    private void teacher_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacher_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
        new teacher().setVisible(true);
    }//GEN-LAST:event_teacher_buttonActionPerformed

    private void reslut_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reslut_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
        new result().setVisible(true);
    }//GEN-LAST:event_reslut_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(class6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(class6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(class6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(class6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new class6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SID_txt;
    private javax.swing.JButton admission_button;
    private javax.swing.JTextField att_mark;
    private javax.swing.JTextField attendance_txt;
    private javax.swing.JLabel class_txt;
    private javax.swing.JComboBox class_type;
    private javax.swing.JButton clear_txt;
    private javax.swing.JTextField ct_parcentage;
    private javax.swing.JTextField ct_txt;
    private javax.swing.JTextField grade_txt;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField mcq_txt;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField passcode_txt;
    private javax.swing.JButton reslut_button;
    private javax.swing.JButton save_txt;
    private javax.swing.JTextField search_id;
    private javax.swing.JComboBox semister;
    private javax.swing.JButton subject_button;
    private javax.swing.JTable subject_table;
    private javax.swing.JComboBox subjectbox;
    private javax.swing.JButton teacher_button;
    private javax.swing.JTextField total_txt;
    private javax.swing.JButton update_button;
    private javax.swing.JTextField written_txt;
    // End of variables declaration//GEN-END:variables
}
